sudo: required

services:
  - docker

before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce
- sudo sh -c "echo \"DOCKER_OPTS='--insecure-registry 172.30.0.0/16'\" >> /etc/default/docker" && sudo service docker restart && sudo mount --make-rshared /
- docker info
- docker version
- docker login -u amazeeiojenkins -p $DOCKERHUB_PASSWORD

install:
- make pull -j6 TAG=$TRAVIS_BRANCH
- docker image ls -a --digests

before_script:
- make start-openshift
- docker logs -f origin &> .openshift-logs &
- make build -j10 TAG=$TRAVIS_BRANCH
- make tag-push -j6 TAG=$TRAVIS_BRANCH &> .push-logs &
- make up
- docker-compose -p lagoon logs -f &> .service-logs &
- sleep 20

script:
- make test -j2

after_script:
- cat .openshift-logs
- cat .push-logs
- cat .service-logs