version: 2
jobs:
  build:
    machine:
      enabled: true
      image: circleci/classic:edge

    steps:
      - checkout

      - run:
          name: check docker
          command: |
            sudo su
            echo "DOCKER_OPTS='--insecure-registry 172.30.0.0/16'" >> /etc/default/docker
            service docker restart
      - run:
          name: Start openshift
          command: |
            sudo ./startOpenShift.sh

      - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker-compose -f docker-compose.ci.yaml up -d