version: 2
jobs:
  build:
    machine:
      enabled: true
      image: circleci/classic:edge

    steps:
      - checkout

      - run:
          name: check docker
          command: |
            cat /etc/init.d/docker
            cat /etc/default/docker

      - run:
          name: Start openshift
          command: |
            ./startOpenShift.sh

      - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker-compose -f docker-compose.ci.yaml up -d