version: 2
jobs:
  build:
    machine:
      enabled: true
      image: circleci/classic:edge

    steps:
      - checkout

      - run:
          name: check docker
          command: |
            sudo sh -c "echo \"DOCKER_OPTS='--insecure-registry 172.30.0.0/16'\" >> /etc/default/docker"
            sudo service docker restart
            sudo mount --make-rshared /
      - run:
          name: Start openshift
          command: |
            sudo ./startOpenShift.sh

      - run:
          name: Start container and verify it's working
          command: |
            set -x
            make build services-build
            docker-compose up -d