version: 2
jobs:
  build:
    machine:
      enabled: true
      image: circleci/classic:edge

    steps:
      - checkout

      - restore_cache:
          keys:
            - images-cache-{{ .Branch }}
            - images-cache

      - run:
          name: load docker images from cache
          command: make images-cache-load

      - run:
          name: check docker
          command: |
            sudo sh -c "echo \"DOCKER_OPTS='--insecure-registry 172.30.0.0/16'\" >> /etc/default/docker"
            sudo service docker restart
            sudo mount --make-rshared /
      - run:
          name: Start openshift
          command: |
            sudo ./startOpenShift.sh

      - run:
          name: Start container and verify it's working
          command: |
            set -x
            make build services-build
            docker-compose up -d

      - run:
          name: Start container and verify it's working
          command: |
            set -x
            make build services-build
            docker-compose up -d

      - run:
          name: save docker images to cache
          command: make images-cache-save

      - save_cache:
          key: images-cache-{{ .Branch }}
          paths:
            - .cache
      - save_cache:
          key: images-cache
          paths:
            - .cache